# Generated by Django 3.2 on 2023-05-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('moderator', 'Moderator'), ('user', 'User'), ('superuser', 'Administrator')], default='user', max_length=100, verbose_name='Роль пользователя'),
        ),
    ]
